[package]
name = "Jericho"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
get_if_addrs = "0.5"
sys-info = "0.9.1"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12.12", features = ["blocking"] }
ipgeolocate = "0.3.5"
